### ISSUE TITLE
One of the labels not highlighted

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/guide-kubernetes-intro#124]
**Guide**: https://openliberty.io/guides/kubernetes-intro.html#deploying-the-microservices

When I hover over `label`, it highlights 2 `labels` fields for the inventory deployment, but only 1 `labels` field for the system deployment. I think the `labels` field which I outlined in red should also be highlighted.

Also, in the guide it calls the field `label`, but in the kubernetes.yaml it's called `labels`.

<img width="1680" alt="Screen Shot 2019-11-25 at 1 23 27 PM" src="https://user-images.githubusercontent.com/33457590/69567339-255bdb80-0f87-11ea-926e-d9ce17f48b7f.png">

**Comment by evelinec** [comment]
All feedback addressed in the latest commits. Check out the changes here: http://lgdev1.fyre.ibm.com:4060/guides/kubernetes-intro.html @jimmy1wu can you review? Thanks.

**Comment by jimmy1wu** [comment]
Verified
