### ISSUE TITLE
Guide needs an update to use new hotspot labelling

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-kubernetes-intro#125]
Brought to attention by issue #124. Guide currently still uses old numbering system.

**Comment by evelinec** [comment]
All feedback addressed in the latest commits. Check out the changes here: http://lgdev1.fyre.ibm.com:4060/guides/kubernetes-intro.html @MaiHameed can you review? Thanks.

**Comment by MaiHameed** [comment]
Addressed.
