### ISSUE TITLE
Dev mode peer review

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-kubernetes-intro#128]
Tested on a fresh Ubuntu 18 install, using the `dev-mode` branch and verified on the lgdev site.

- [x] command substitutions should use the following command syntax `$(command)` vs `'command'` as shown:
![image](https://user-images.githubusercontent.com/26514093/72097946-7af80780-32eb-11ea-8bdd-011530a22068.png)

- [x] Since we're updating the guide, might as well address hotspot issues, numbers #125 #124.

**Comment by evelinec** [comment]
I had setup a Ubuntu 16 machine, and the command worked fine. @gkwan-ibm what do you think?

**Comment by evelinec** [comment]
The command substitutions issue is to be handled all together in https://github.com/OpenLiberty/guides-common/issues/383.

**Comment by evelinec** [comment]
Feedback is addressed in the latest commits. Check out the changes here: http://lgdev1.fyre.ibm.com:4060/guides/kubernetes-intro.html @MaiHameed can you review? Thanks.

**Comment by evelinec** [comment]
Fixed command substitutions in https://github.com/OpenLiberty/guide-kubernetes-intro/pull/127/commits/6f21f063938cc8839bc4e18b0fd0ff8bc6c6b03e. @MaiHameed can you review? Thanks.

**Comment by MaiHameed** [comment]
Addressed.
