### ISSUE TITLE
dev mode peer review - macOS

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/guide-kubernetes-intro#129]
- [x] Extra period between inventory and Kubernetes Service
<kbd>
<img width="533" alt="Screen Shot 2020-01-09 at 3 36 23 PM" src="https://user-images.githubusercontent.com/33457590/72102813-daf3ab80-32f5-11ea-8d2d-35f9d1f63344.png">
</kbd>

<hr />

- [x] I think `Deployment` should be lowercase 
<kbd>
<img width="545" alt="Screen Shot 2020-01-09 at 3 42 10 PM" src="https://user-images.githubusercontent.com/33457590/72104526-9d911d00-32f9-11ea-9f3c-fd4df7e151ee.png">
</kbd>

<hr />

- [x] `docker` should be `Docker` and `system` should be wrapped with ``
<kbd>
<img width="533" alt="Screen Shot 2020-01-09 at 3 42 22 PM" src="https://user-images.githubusercontent.com/33457590/72104584-c31e2680-32f9-11ea-9ec1-28a0d7ab3ece.png">
</kbd>

<hr />

- [x] Plugin version not found. I think the groupId should be `<groupId>io.openliberty.tools</groupId>`
<kbd>
<img width="696" alt="Screen Shot 2020-01-09 at 4 00 27 PM" src="https://user-images.githubusercontent.com/33457590/72104442-70dd0580-32f9-11ea-9eed-00b5216ea86c.png">
<img width="1680" alt="Screen Shot 2020-01-09 at 4 01 09 PM" src="https://user-images.githubusercontent.com/33457590/72104435-6cb0e800-32f9-11ea-965f-409fc29820f5.png">
</kbd>

<hr />

- [x] The command should be `mvn failsafe:integration-test -Ddockerfile.skip=true -Dcluster.ip=localhost`

<kbd>
<img width="563" alt="Screen Shot 2020-01-10 at 10 48 14 AM" src="https://user-images.githubusercontent.com/33457590/72166147-ba2f6280-3396-11ea-8ee4-ed769350fac6.png">
</kbd>

**Comment by evelinec** [comment]
Regarding the `dockerfile.skip` parameter, checked with @gkwan-ibm that it's no longer needed, because the docker images are not built with the `dockerfile-maven-plugin` anymore. The text, `The dockerfile.skip parameter is set to true in order to skip building a new Docker image.` is removed.

**Comment by evelinec** [comment]
All feedback addressed in the latest commits. Check out the changes here: http://lgdev1.fyre.ibm.com:4060/guides/kubernetes-intro.html

**Comment by jimmy1wu** [comment]
Verified ✅
