### ISSUE TITLE
Is something missing from the section: "Next you will make requests to your services."

### ISSUE THREAD

**Issue by djhallx** [OpenLiberty/guide-kubernetes-intro#208]
I have been walking through this guide and everything seems to be working up to the point where I am supposed to be able to connect to the running services. This step does not appear to work. Is there a missing step prior to this to expose the ip addresses?

If I run: `minikube service --all --ulr` I get the following:

😿  service default/hello-world has no node port
😿  service default/hello-world-nodes has no node port
😿  service default/kubernetes has no node port
|-----------|-------------------|--------------|---------------------------|
| NAMESPACE |       NAME        | TARGET PORT  |            URL            |
|-----------|-------------------|--------------|---------------------------|
| default   | hello-world         | No node port     |
| default   | hello-world-nodes | No node port  |
| default   | inventory-service |         9080          | http://192.168.49.2:32000 |
| default   | kubernetes          | No node port     |
| default   | system-service    |         9080           | http://192.168.49.2:31000 |
|-----------|-------------------|--------------|---------------------------|
🏃  Starting tunnel for service hello-world.
🏃  Starting tunnel for service hello-world-nodes.
🏃  Starting tunnel for service inventory-service.
🏃  Starting tunnel for service kubernetes.
🏃  Starting tunnel for service system-service.
❗  Because you are using a Docker driver on windows, the terminal needs to be open to run it.

I then try to open "http://192.168.49.2:31000" to connect to the system-service in a browser and it times out.

What am I missing?

**Comment by gkwan-ibm** [comment]
hi @djhallx 
would you tell us which platform you used and give us following?
```
mvn -version
minikube version
```

**Comment by djhallx** [comment]
mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T14:49:05-05:00)
Maven home: D:\Root\Tools\maven\apache-maven-3.5.3-bin\apache-maven-3.5.3\bin\..
Java version: 14, vendor: Oracle Corporation
Java home: D:\Root\Tools\Java\jdk-14
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

minikube version: v1.25.2

Another note... I am also using Docker for Windows and I'm reading that things get "more complicated" between minikube and Docker. I can ssh into minikube and access my services using curl and I get the expected web page text. But from chrome, running in Windows, outside of minikube, I can't seem to connect to any of the node ports.

This may all be user error. Not sure yet.

**Comment by gkwan-ibm** [comment]
hi @djhallx 

As the guide described, Dockerdesktop is preferable for Windows. We need time to investigate by using minikube. Instead, you can try our cloud-hosted version without setting up any prerequisites. To launch the lab, click the "Run in cloud" button that located at the top "Prerequisites" section of the right side.

**Comment by gkwan-ibm** [comment]
hi @djhallx 

By the way, did you try [kubernetes port-forward](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#forward-a-local-port-to-a-port-on-the-pod) to access the running service?

**Comment by djhallx** [comment]
Yes, I did eventually figure out that I needed to use port-forwarding. The other issue that I think might be relevant is that the two services did not have "externalIPs" IP addresses as defined in the kubernetes.yaml file provided in the example. When I ran "kubectl get svc" the column for "EXTERNAL-IP" was "none" for all entries. I then added an "externalIPs" entry for each service in the kubernetes.yaml file and now when I run "kubectl get svc" I get:

```
kubectl get svc
NAME                         TYPE             CLUSTER-IP         EXTERNAL-IP              PORT(S)                                          AGE
hello-world                 ClusterIP       10.107.228.58     <none>                      5672/TCP,15672/TCP,15692/TCP   2d13h
hello-world-nodes     ClusterIP        None                  <none>                      4369/TCP,25672/TCP                     2d13h
inventory-service       NodePort      10.98.223.206      192.168.90.2              9080:32000/TCP                             13h
kubernetes                 ClusterIP       10.96.0.1              <none>                     443/TCP                                          2d13h
system-deployment   ClusterIP       10.100.2.224        <none>                     31000/TCP                                     35h
system-service           NodePort      10.108.178.131    192.168.90.1              9080:31000/TCP                            13h
```

Which looks like what I want. But when I try to access the service from Chrome (outside of minikube) I am still unable to access the services. 
I'm not giving up. I'll figure this out... Thanks for you help.

**Comment by gkwan-ibm** [comment]
hi @djhallx I am curious which Docker you are using? Docker from DockerDesktop? Or docker client with a Linux box?

**Comment by gkwan-ibm** [comment]
hi @djhallx we are closing this issue. You may reopen it and provide information for my [questions](https://github.com/OpenLiberty/guide-kubernetes-intro/issues/208#issuecomment-1118978521).
