### ISSUE TITLE
Error after updating the images names and nodePorts

### ISSUE THREAD

**Issue by ozcanli** [OpenLiberty/guide-kubernetes-intro#223]
I had following error when I updated the image names with the following commands:

sed -i 's=system:1.0-SNAPSHOT=us.icr.io/'"$SN_ICR_NAMESPACE"'/system:1.0-SNAPSHOT\n        imagePullPolicy: Always=g' kubernetes.yaml
sed -i 's=inventory:1.0-SNAPSHOT=us.icr.io/'"$SN_ICR_NAMESPACE"'/inventory:1.0-SNAPSHOT\n        imagePullPolicy: Always=g' kubernetes.yaml
sed -i 's=nodePort: 31000==g' kubernetes.yaml
sed -i 's=nodePort: 32000==g' kubernetes.yaml

theia@theiadocker-ozcanli:/home/project/guide-kubernetes-intro/start$ kubectl get pods
NAME                                    READY   STATUS         RESTARTS   AGE
inventory-deployment-687448ffb9-mwpq7   0/1     ErrImagePull   0          14s
system-deployment-575975cff6-wvjdq      0/1     ErrImagePull   0          14s
theia@theiadocker-ozcanli:/home/project/guide-kubernetes-intro/start$ kubectl describe pods
Name:                 inventory-deployment-687448ffb9-mwpq7
Namespace:            sn-labs-ozcanli
Priority:             1
Priority Class Name:  normal
Node:                 10.241.64.63/10.241.64.63
Start Time:           Fri, 26 Aug 2022 11:19:07 +0000
Labels:               app=inventory
                      pod-template-hash=687448ffb9
Annotations:          cni.projectcalico.org/containerID: dc054a4544bfcac26d67d733dc6a98502079f2382210c036f68697a93d64c8b3
                      cni.projectcalico.org/podIP: 172.17.188.245/32
                      cni.projectcalico.org/podIPs: 172.17.188.245/32
                      kubernetes.io/limit-ranger:
                        LimitRanger plugin set: cpu, ephemeral-storage, memory request for container inventory-container; cpu, ephemeral-storage, memory limit for...
                      kubernetes.io/psp: ibm-privileged-psp
Status:               Pending
IP:                   172.17.188.245
IPs:
  IP:           172.17.188.245
Controlled By:  ReplicaSet/inventory-deployment-687448ffb9
Containers:
  inventory-container:
    Container ID:   
    Image:          us.icr.io/sn-labs-ozcanli/inventory:1.0-SNAPSHOT
    Image ID:       
    Port:           9080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:                500m
      ephemeral-storage:  5Gi
      memory:             512Mi
    Requests:
      cpu:                200m
      ephemeral-storage:  512Mi
      memory:             128Mi
    Environment:
      SYS_APP_HOSTNAME:  system-service
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ww4k7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-ww4k7:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 600s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 600s
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  21s               default-scheduler  Successfully assigned sn-labs-ozcanli/inventory-deployment-687448ffb9-mwpq7 to 10.241.64.63
  Normal   BackOff    18s               kubelet            Back-off pulling image "us.icr.io/sn-labs-ozcanli/inventory:1.0-SNAPSHOT"
  Warning  Failed     18s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    4s (x2 over 20s)  kubelet            Pulling image "us.icr.io/sn-labs-ozcanli/inventory:1.0-SNAPSHOT"
  Warning  Failed     3s (x2 over 19s)  kubelet            Failed to pull image "us.icr.io/sn-labs-ozcanli/inventory:1.0-SNAPSHOT": rpc error: code = NotFound desc = failed to pull and unpack image "us.icr.io/sn-labs-ozcanli/inventory:1.0-SNAPSHOT": failed to resolve reference "us.icr.io/sn-labs-ozcanli/inventory:1.0-SNAPSHOT": us.icr.io/sn-labs-ozcanli/inventory:1.0-SNAPSHOT: not found
  Warning  Failed     3s (x2 over 19s)  kubelet            Error: ErrImagePull

Name:                 system-deployment-575975cff6-wvjdq
Namespace:            sn-labs-ozcanli
Priority:             1
Priority Class Name:  normal
Node:                 10.241.64.63/10.241.64.63
Start Time:           Fri, 26 Aug 2022 11:19:06 +0000
Labels:               app=system
                      pod-template-hash=575975cff6
Annotations:          cni.projectcalico.org/containerID: ceca5ddacacb74d49c02f72ead7f8b57482098d0709432a2c40ca50d79845b6d
                      cni.projectcalico.org/podIP: 172.17.188.227/32
                      cni.projectcalico.org/podIPs: 172.17.188.227/32
                      kubernetes.io/limit-ranger:
                        LimitRanger plugin set: cpu, ephemeral-storage, memory request for container system-container; cpu, ephemeral-storage, memory limit for co...
                      kubernetes.io/psp: ibm-privileged-psp
Status:               Pending
IP:                   172.17.188.227
IPs:
  IP:           172.17.188.227
Controlled By:  ReplicaSet/system-deployment-575975cff6
Containers:
  system-container:
    Container ID:   
    Image:          us.icr.io/sn-labs-ozcanli/system:1.0-SNAPSHOT
    Image ID:       
    Port:           9080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:                500m
      ephemeral-storage:  5Gi
      memory:             512Mi
    Requests:
      cpu:                200m
      ephemeral-storage:  512Mi
      memory:             128Mi
    Environment:          <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lk2rt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-lk2rt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 600s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 600s
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  22s               default-scheduler  Successfully assigned sn-labs-ozcanli/system-deployment-575975cff6-wvjdq to 10.241.64.63
  Normal   BackOff    17s               kubelet            Back-off pulling image "us.icr.io/sn-labs-ozcanli/system:1.0-SNAPSHOT"
  Warning  Failed     17s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    5s (x2 over 19s)  kubelet            Pulling image "us.icr.io/sn-labs-ozcanli/system:1.0-SNAPSHOT"
  Warning  Failed     4s (x2 over 18s)  kubelet            Failed to pull image "us.icr.io/sn-labs-ozcanli/system:1.0-SNAPSHOT": rpc error: code = NotFound desc = failed to pull and unpack image "us.icr.io/sn-labs-ozcanli/system:1.0-SNAPSHOT": failed to resolve reference "us.icr.io/sn-labs-ozcanli/system:1.0-SNAPSHOT": us.icr.io/sn-labs-ozcanli/system:1.0-SNAPSHOT: not found
  Warning  Failed     4s (x2 over 18s)  kubelet            Error: ErrImagePull
theia@theiadocker-ozcanli:/home/project/guide-kubernetes-intro/start$

**Comment by jakub-pomykala** [comment]
Hi @ozcanli - thank you for opening this issue.

We had checked it out and it looks like the docker push commands given at the end of "Building and containerizing the microservices" step either didn't run at all or didn't run successfully.

These are the docker commands:
```
docker tag inventory:1.0-SNAPSHOT us.icr.io/$SN_ICR_NAMESPACE/inventory:1.0-SNAPSHOT
docker tag system:1.0-SNAPSHOT us.icr.io/$SN_ICR_NAMESPACE/system:1.0-SNAPSHOT
docker push us.icr.io/$SN_ICR_NAMESPACE/inventory:1.0-SNAPSHOT
docker push us.icr.io/$SN_ICR_NAMESPACE/system:1.0-SNAPSHOT
```

If you could try again and let us know whether you still have the same issue. TYIA

**Comment by gkwan-ibm** [comment]
Hi @ozcanli 

We are closing this issue. If you still have problem, you may reopen this issue or open a new issue.
