### ISSUE TITLE
Develop Cloud Native apps on OpenShift with Open Liberty

### ISSUE THREAD

**Issue by fcasamento** [OpenLiberty/guide-kubernetes-intro#230]
Lab 2: Develop Cloud Native apps on OpenShift with Open Liberty
[https://compete.ide.skillsnetwork.site/competitions/build-smart-on-kubernetes-challenge](url)

Hello, I don't know if I did the wrong lab, but when following the steps it shows an error when fetching the image. I followed the suggested steps correctly. I know that a wrong item does not make me complete the activity. Should I change the image that the file suggested?

theia@theiadocker-casamento:/home/project/guide-kubernetes-intro/start$ kubectl get pods
NAME                                    READY   STATUS             RESTARTS   AGE
inventory-deployment-6fd48545f4-kmnc6   0/1     ImagePullBackOff   0          7s
system-deployment-6594d9c887-q4djs      0/1     ImagePullBackOff   0          7s

**Comment by jakub-pomykala** [comment]
Hi @fcasamento - thank you for opening this issue.

We had checked it out and it looks like the docker push commands given at the end of "Building and containerizing the microservices" step either didn't run at all or didn't run successfully.

These are the docker commands:
```
docker tag inventory:1.0-SNAPSHOT us.icr.io/$SN_ICR_NAMESPACE/inventory:1.0-SNAPSHOT
docker tag system:1.0-SNAPSHOT us.icr.io/$SN_ICR_NAMESPACE/system:1.0-SNAPSHOT
docker push us.icr.io/$SN_ICR_NAMESPACE/inventory:1.0-SNAPSHOT
docker push us.icr.io/$SN_ICR_NAMESPACE/system:1.0-SNAPSHOT
```

If you could try again and let us know whether you still have the same issue. TYIA

**Comment by gkwan-ibm** [comment]
hi @fcasamento

We are closing this issue. If you still have problem, you may reopen this issue or open a new issue.
