### ISSUE TITLE
Failed to Inject @ConfigProperty for key SYS_APP_HOSTNAME

### ISSUE THREAD

**Issue by emeraldhieu** [OpenLiberty/guide-kubernetes-intro#236]
I've managed to build docker images and applied the kubernetes.yaml.
The system app works fine
```
% kubectl wait --for=condition=ready pod -l app=system
pod/system-deployment-86f67f8948-rn88b condition met
```
but the inventory app doesn't
```
 % kubectl wait --for=condition=ready pod -l app=inventory
error: timed out waiting for the condition on pods/inventory-deployment-6657bb46ff-b2vg9
```

Logs of the Pod inventory shows:
```
start % kubectl logs inventory-deployment-6657bb46ff-b2vg9  

Launching defaultServer (Open Liberty 23.0.0.1/wlp-1.0.73.cl230120230123-2118) on Eclipse OpenJ9 VM, version 11.0.17+8 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://inventory-deployment-6657bb46ff-b2vg9:9080/health/
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application guide-kubernetes-intro-inventory. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: SRCFG02000: Failed to Inject @ConfigProperty for key SYS_APP_HOSTNAME into io.openliberty.guides.inventory.health.InventoryReadinessCheck.hostname since the config property could not be found in any config source
[AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-3.0, concurrent-2.0, jndi-1.0, json-1.0, jsonb-2.0, jsonp-2.0, mpConfig-3.0, mpHealth-4.0, restfulWS-3.0, restfulWSClient-3.0, servlet-5.0].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 5.927 seconds.
[WARNING ] CWMMH0053W: The readiness health check reported a DOWN overall status because the following applications are not started yet: [guide-kubernetes-intro-inventory]
```

It looks like inventory app needs the deployed host of the system app. How can I pass a value to SYS_APP_HOSTNAME?
Is this error expected?

---
Environment: MacOS, Docker Desktop, Minikube.

**Comment by emeraldhieu** [comment]
Okay, not sure if the issue is intentional. I got it worked by creating a configmap with `SYS_APP_HOSTNAME`. These are the steps:

Get the hostname of system app
```
start % kubectl describe service system-service              
Name:                     system-service
...
Endpoints:                10.244.0.50:9080
...
```

Create a config map with `SYS_APP_HOSTNAME= 10.244.0.50`
```
kubectl create configmap sys-app-name --from-literal SYS_APP_HOSTNAME=10.244.0.50
```

Roll out the deployment (restart with new config map)
```
kubectl rollout restart deployment/inventory-deployment
```

Return a URL to connect the service in local cluster (This is needed for Docker Desktop on Mac).
```
minikube service inventory-service --url
http://127.0.0.1:52188
```

Curl the inventory app to check if it's working
```
curl http://127.0.0.1:52188/inventory/systems/system-service
```

If it prints a JSON of system properties, it's working. Otherwise, check the logs.

**Comment by Genzer** [comment]
@emeraldhieu : How did you deploy the apps into Kubernetes? Which manifests did you use?

The `finish/kubernetes.yaml` contains the settings for the environment variable.

https://github.com/OpenLiberty/guide-kubernetes-intro/blob/a5fe17d3d977694e59ebb46249c5614bea1ba4df/finish/kubernetes.yaml#L113

**Comment by gkwan-ibm** [comment]
Thanks @Genzer answered.

Yes, the inventory service requires the system service. The problem was the readiness check of the inventory failed. The check gets the system hostname by the [SYS_APP_HOSTNAME](https://github.com/OpenLiberty/guide-kubernetes-intro/blob/prod/finish/inventory/src/main/java/io/openliberty/guides/inventory/health/InventoryReadinessCheck.java#L37) configuration property. When deploy the inventory service to the containerized environments, the `SYS_APP_HOSTNAME` is provided through environment variable in the kubernetes.yaml file as Genzer mentioned in above. Of course, using configmap also works.
