### ISSUE TITLE
Improve SEO for this guide

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/guide-kubernetes-intro#67]
We can improve the SEO for a direct link to this guide.  I believe these are the attributes with some examples from an existing OL.io blog post

```
seo-title: Build and push Spring Boot Docker images with boost-maven-plugin - OpenLiberty.io
seo-description: Efficiently build and push layered Docker images of Spring Boot applications using the Boost Maven plugin.
```

**Comment by evelinec** [comment]
We'll consider SEO for all guides all together. Close this issue for now.
