### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-kubernetes-intro#68]
- [x] "Make sure you have the Docker version with the Docker Desktop support" -> "Make sure you have a Docker version with Docker Desktop support." 

The way it is currently makes it sound like there is only one version of Docker that has Docker Desktop support.

----

- [x] After following the instructions and running `docker images`, I noticed that `gcr.io/google_containers/defaultbackend` wasn't listed when looking through the results of the command.

I realize the guide says to verify `name:1.0-SNAPSHOT` and `name:1.0-SNAPSHOT` are among the list (which they were), but I am not sure there is a point listing out images in the guide output that aren't present.

----

- [x] "Scaling is one of the primary advantages of Kubernetes because replicating your application allows it to accommodate more traffic, **and then descale your deployments to free up resources when the traffic decreases.**"

But in the guide it only shows how to scale and doesn't actually demonstrate how to descale your deployments. Perhaps you can provide more details in the scaling section (as suggested here https://github.com/OpenLiberty/guide-kubernetes-intro/issues/63) and explain the `--replicas=3` part of the command and how decreasing the replicas allows you to descale? Or w.e. the correct way to descale your deployments in kubernetes is.

----

- [x] Only 1 name pod running after redeploy

I understand this is expected behaviour, but perhaps it might be worth mentioning. Since the section before this is "Scaling a deployment" and someone might expect to see 3 name pods after redeploying. Or even just as a friendly reminder that after redeploying, you will have to rescale.

**Comment by yeekangc** [comment]
@proubatsis, I thought "Make sure you have the Docker version with the Docker Desktop support" is fixed?

We should either say use a Docker Desktop version with Kubernetes support or use the latest version.

**Comment by yeekangc** [comment]
Thank you, @proubatsis.  I reviewed, approved and merged.  The next OL.io refresh should pick it up.

**Comment by proubatsis** [comment]
PR Merged
