### ISSUE TITLE
The test script isn't working on MacOS 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-kubernetes-intro#85]
Setting environment variables from .travis.yml
$ export CHANGE_MINIKUBE_NONE_USER=true
$ java -Xmx32m -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
$ javac -J-Xmx32m -version
javac 10.0.1
before_script.1
0.01s$ unset _JAVA_OPTIONS
before_script.2
0.04s$ cd finish
0.05s$ sudo mount --make-rshared /
mount: illegal option -- -
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
The command "sudo mount --make-rshared /" failed and exited with 1 during .

**Comment by gkwan-ibm** [comment]
Let try to run travisTest.sh locally.

**Comment by gkwan-ibm** [comment]
The travis.yml and travisTest.sh should be good if run on Linux. No plan to update them to run on MacOS for this moment.
