### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-kubernetes-intro#90]
- [x] Guide fails with Java 11 (needs to be synchronized with master branch). `pom.xml` hotspots would then need to get updated.

**Prerequisites** 
- [x] None of the links in this section open in a new tab

**Deploying the microservices**
- [ ] `name:1.0-SNAPSHOT` is in blue text but `ping:1.0-SNAPSHOT` is in black text. Both these lines get highlighted at the same time with one hotspot, so the difference will be obvious to the user.
![image](https://user-images.githubusercontent.com/22628575/52791168-58576300-3036-11e9-94fd-3998f121473b.png)

NOTE: Same issue with `containerPort` for the deployments

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guides-common/pull/233/

**Comment by justineechen** [comment]
The color difference is a UI issue, I opened an issue here: https://github.com/OpenLiberty/openliberty.io/issues/991 
It's very strange, it actually changes color only after you hover over the hotspot but when you look at the file in the beginning it's still blue.

**Comment by andrewdes** [comment]
Guide no longer fails with Java 11 after syncing multipane branch with master (multipane branch was missing Java 11 dependencies). Re-reviewed the guide and everything looks good, closing the issue and will track the UI issue separately.
