### ISSUE TITLE
Multipane - Post-publish test

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/guide-kubernetes-intro#91]
- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on test site, ie, qa-guides
- [x] Read through the guide 
- [x] Clone repo and test finish directory with no error
- [ ] Run `diff -r start/ finish/` 
- [x] Follow the instruction in the guide to test that it is working
- [x] Use the `copy` buttons instead of typing 
- [x] Links open in new tab
- [x] Action arrows do not highlight any code
- [x] Update action arrows have hotspotted text underneath
- [x] Full files mentioned in the guide as hotspots should not highlight any code
- [x] Hovering over code commands should switch to the right file

**Comment by proubatsis** [comment]
* There are `pom.xml` differences between `finish/` and `start/`

**Comment by andrewdes** [comment]
Merged here: https://github.com/OpenLiberty/guide-kubernetes-intro/pull/92
